defaultPortal: hlaprint-for-information-technology
portals:
  - name: hlaprint-for-information-technology
    portalId: 243882690
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CILv97iVMxIgQlNQMl8kQEwrAhMACAkCFBwBAgEQAwoBAgMHGygCeAEYwrWldCCy9-EnKO7pDDIUipMtU5L6PKwdo0ZE-FbfG7JJskk6WEJTUDJfJEBMKwImABATBgAGAHEAKwBIAAEAAQABAAgAAQAGAAIAFAAEABgABAABAAEAAQABAAEABAABAAUAAQASAAkAAwABADEAAQBXABcAAQBCAFQBAQBCFPyzsbS5qpUCdMhBB6WevrEBgYc5SgNuYTJSAFoAYAFosvfhJ3AAeAA
        expiresAt: "2025-09-17T10:00:05.806Z"
    accountType: STANDARD
    personalAccessKey: >-
      CiRuYTItZTlmOS0yZTNkLTQxY2YtOGUxOC1hZWYwYjcxNTQ5NTkQwrWldBiy9-EnKhkABeaRgkrjp3qkZHXuF-OZL9msxmENRGuySgNuYTI
