defaultPortal: hlaprint-for-information-technology
portals:
  - name: hlaprint-for-information-technology
    portalId: 243882690
    env: prod
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-

        expiresAt: "2025-09-17T10:00:05.806Z"
    accountType: STANDARD
    personalAccessKey: >-
